#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "feber"
name = "Feber"
description.en = "Simple group calendar"
description.fr = "Calendrier de groupe simpliste"

version = "1.2.4~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
demo ="https://simonrepp.com/feber/demo/"
website = "https://simonrepp.com/feber/"
code = "https://codeberg.org/simonrepp/feber"
fund = "https://ko-fi.com/simonrepp"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "60K"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/feber"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/simonrepp/feber/archive/1.2.4.tar.gz"
    sha256 = "89136ddc3479f1c253620fab48a79f08338f773d947054cdb4f871e130ee7359"

    autoupdate.strategy = "latest_forgejo_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3-fpm, php8.3-mbstring"
